version: "3.9"

services:
# Prefect metadata database
  prefect-postgres:
    image: postgres:14
    container_name: prefect-postgres
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - prefect-network

# Prefect Server (API + UI + Scheduler)
  prefect-server:
    image: prefecthq/prefect:3.6.16-python3.11
    container_name: prefect-server
    depends_on:
      prefect-postgres:
        condition: service_healthy
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@prefect-postgres:5432/prefect
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_API_URL: http://localhost:4200/api
      PREFECT_ANALYTICS_ENABLED: "false"
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    restart: unless-stopped
    networks:
      - prefect-network

# Prefect Worker (process)
  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prefect-worker
    depends_on:
      prefect-server:
        condition: service_started
    environment:
      PREFECT_API_URL: http://localhost:4200/api
    env_file:
      - .env
    restart: on-failure
    network_mode: host
    # networks:
    #  - prefect-network

# Analytics / Lakehouse Postgres
  analytics-postgres:
    image: postgres:16
    container_name: analytics-postgres
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      POSTGRES_DB: analytics
    ports:
      - "5434:5432"
    volumes:
      - analytics_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics -d analytics"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - prefect-network

# Analytics DB migrations (init container)
  analytics-migrations:
    image: postgres:16
    container_name: analytics-migrations
    depends_on:
      analytics-postgres:
        condition: service_healthy
    volumes:
      - ./sql/migrations:/migrations
    environment:
      PGPASSWORD: analytics
    entrypoint: >
      bash -c "
      for file in /migrations/*.sql; do
        echo Running migration: $$file;
        psql -h analytics-postgres -U analytics -d analytics -f $$file;
      done
      "
    restart: "no"
    networks:
      - prefect-network

volumes:
  postgres_data:
  analytics_postgres_data:

networks:
  prefect-network:
    driver: bridge
